### ISSUE TITLE
Can I create a lobby and manage it using this library?

### ISSUE THREAD

**Issue by Vladislav719** [TJRoger/node-dota2-spectator#4]
Can I create a lobby and manage it using this library? Is it possible.
It is one of the current existing libraries that works fine, without any error on login phase. But I don't know how to do that.

**Comment by TJRoger** [comment]
You can add the handler to this repo to fulfils your demand

**Comment by TJRoger** [comment]
@Vladislav719 I have added a handler to my repo, you can give it a try now.

**Comment by Vladislav719** [comment]
@TJRoger wow, I will try soon, and then say you about results. Otherwise thanks you
